# Generated by Django 3.1.6 on 2021-02-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price_per_day',
            field=models.IntegerField(),
        ),
    ]
