# Generated by Django 3.1.6 on 2021-02-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpass', '0002_auto_20210213_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
