# Generated by Django 3.1.6 on 2021-02-13 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carpass', '0003_car_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='booked_by',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
