# Generated by Django 3.1.6 on 2021-02-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpass', '0004_car_booked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='booked_by',
            field=models.IntegerField(),
        ),
    ]
