# Generated by Django 3.1.6 on 2021-02-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpass', '0005_auto_20210213_1442'),
    ]

    operations = [
    ]
